name: fix_me_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_dialogflow: ^0.1.3
  flutter_rating_bar: ^3.0.1+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_database: ^3.1.3
  google_map_polyline: ^0.2.0+1
  google_sign_in: ^4.4.3
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+4
  location: ^2.3.5
  permission: ^0.1.7
  geolocator: ^5.3.1

  flutter_credit_card: ^0.1.3
  provider: ^5.0.0
  image_picker: ^0.6.7+22
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image-front.png
    - assets/googlelogin.png
    - assets/fblogin.png
    - assets/applelogin.png
    - assets/currentLocation.png
    - assets/breakdown_btn.png
    - assets/fuelempty_btn.png
    - assets/navigate_btn.png
    - assets/chatbot.png
    - assets/car.png
    - assets/fixbot-vdj9-6dd3b6aa7052.json
